name: flowdo
description: "FlowDo - Fluid Todo App with GPU liquid shader background for Android ARM64"
publish_to: 'none'
version: 2.4.0+5

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/flowdo-icon-foreground-v2.png
  shaders:
    - shaders/fluid.frag
